version: '3'
services:
  react-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - finance_network

networks:
  finance_network: